"""Tests for the lockfile / parsed-manifest coverage gate.

No network. Every fixture is a synthetic repository under ``tmp_path``.

The gate exists because ``environments/requirements.lock`` is installed from but
is not parsed by GitHub's dependency graph, so anything pinned only there is
permanently invisible to Dependabot. These tests are the load-bearing half: if
they cannot fail, the gate is decoration.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = REPO_ROOT / "tools" / "check_lock_manifest_coverage.py"

_spec = importlib.util.spec_from_file_location("check_lock_manifest_coverage", MODULE_PATH)
assert _spec is not None and _spec.loader is not None
gate = importlib.util.module_from_spec(_spec)
sys.modules["check_lock_manifest_coverage"] = gate
_spec.loader.exec_module(gate)

BACKSLASH = chr(92)


# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def write(root: Path, rel: str, text: str) -> Path:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def pinned(name: str, version: str = "1.0.0", hashed: bool = False) -> str:
    """One requirement, optionally in the hashed continuation shape uv emits."""
    if not hashed:
        return "{}=={}\n".format(name, version)
    return (
        "{}=={} {}\n".format(name, version, BACKSLASH)
        + "    --hash=sha256:{} {}\n".format("a" * 64, BACKSLASH)
        + "    --hash=sha256:{}\n".format("b" * 64)
        + "    # via something\n"
    )


def make_repo(tmp_path: Path, lock_names, manifest_names, hashed: bool = True) -> Path:
    """A synthetic repo: one unparsed lock plus one parsed requirements manifest."""
    root = tmp_path / "repo"
    root.mkdir(exist_ok=True)
    write(
        root,
        "environments/requirements.lock",
        "# autogenerated\n" + "".join(pinned(n, hashed=hashed) for n in lock_names),
    )
    write(
        root,
        "requirements.txt",
        "# parsed by GitHub\n" + "".join(pinned(n, hashed=hashed) for n in manifest_names),
    )
    return root


def run_gate(root: Path, **kwargs):
    return gate.run(root, kwargs.pop("lock", "environments/requirements.lock"), kwargs.pop("follow_includes", False))


# ---------------------------------------------------------------------------
# PEP 503 normalization
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("Flask_Login", "flask-login"),
        ("flask-login", "flask-login"),
        ("flask.login", "flask-login"),
        ("FLASK__LOGIN", "flask-login"),
        ("zope.interface", "zope-interface"),
        ("ruamel.yaml.clib", "ruamel-yaml-clib"),
        ("PyYAML", "pyyaml"),
        ("typing_extensions", "typing-extensions"),
    ],
)
def test_normalize_follows_pep503(raw, expected):
    assert gate.normalize(raw) == expected


def test_normalization_equivalence_passes_end_to_end(tmp_path):
    """Flask_Login in the lock against flask-login in a manifest must PASS.

    Getting normalization wrong here manufactures a false failure, which is the
    fastest way to get a gate switched off.
    """
    root = make_repo(tmp_path, lock_names=["Flask_Login", "flask.login-Extra"], manifest_names=["flask-login", "FLASK_LOGIN.EXTRA"])
    code, report = run_gate(root)
    assert report["uncovered"] == []
    assert code == gate.EXIT_OK


def test_normalization_does_not_collapse_distinct_projects(tmp_path):
    """A collapse that is too aggressive would hide a real gap."""
    root = make_repo(tmp_path, lock_names=["flask-login2"], manifest_names=["flask-login"])
    code, report = run_gate(root)
    assert code == gate.EXIT_FINDINGS
    assert [item["normalized"] for item in report["uncovered"]] == ["flask-login2"]


# ---------------------------------------------------------------------------
# The core coverage question
# ---------------------------------------------------------------------------


def test_fully_covered_lock_passes(tmp_path):
    root = make_repo(tmp_path, lock_names=["alpha", "beta", "gamma"], manifest_names=["alpha", "beta", "gamma", "delta"])
    code, report = run_gate(root)
    assert code == gate.EXIT_OK
    assert report["status"] == "ok"
    assert report["locked_distribution_count"] == 3
    assert report["covered_count"] == 3
    assert report["uncovered"] == []


def test_lock_only_package_fails_and_is_named(tmp_path):
    root = make_repo(tmp_path, lock_names=["alpha", "orphan-pkg", "beta"], manifest_names=["alpha", "beta"])
    code, report = run_gate(root)
    assert code == gate.EXIT_FINDINGS
    assert report["status"] == "findings"
    assert len(report["uncovered"]) == 1
    finding = report["uncovered"][0]
    assert finding["name"] == "orphan-pkg"
    assert finding["normalized"] == "orphan-pkg"
    assert finding["lock_line"] > 0
    assert "orphan-pkg" in finding["lock_text"]

    text = gate.render(report, code)
    assert "orphan-pkg" in text
    assert "Dependabot cannot see" in text
    assert "environments/requirements.lock line {}".format(finding["lock_line"]) in text


def test_lock_only_package_reports_the_correct_line(tmp_path):
    root = make_repo(tmp_path, lock_names=["alpha", "orphan-pkg"], manifest_names=["alpha"], hashed=True)
    code, report = run_gate(root)
    assert code == gate.EXIT_FINDINGS
    lineno = report["uncovered"][0]["lock_line"]
    physical = (root / "environments/requirements.lock").read_text(encoding="utf-8").splitlines()
    assert physical[lineno - 1].startswith("orphan-pkg==")


def test_pyproject_alone_can_cover_the_lock(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", pinned("Torch-Geometric", "2.7.0", hashed=True))
    write(
        root,
        "pyproject.toml",
        '[build-system]\nrequires = ["setuptools>=83.0.0"]\n'
        '[project]\nname = "x"\nversion = "1"\n'
        'dependencies = ["torch_geometric>=2.5.0 ; python_version >= \'3.11\'"]\n'
        "[project.optional-dependencies]\ngnn = [\"transformers>=4.30.0\"]\n",
    )
    code, report = run_gate(root)
    assert code == gate.EXIT_OK
    assert report["covered_count"] == 1


def test_pyproject_optional_and_build_system_both_count(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", pinned("setuptools", "84.0.0") + pinned("streamlit", "1.35.0"))
    write(
        root,
        "pyproject.toml",
        '[build-system]\nrequires = ["setuptools>=83.0.0", "wheel"]\n'
        '[project]\nname = "x"\nversion = "1"\ndependencies = []\n'
        '[project.optional-dependencies]\ndemo = ["streamlit>=1.35.0"]\n',
    )
    code, _ = run_gate(root)
    assert code == gate.EXIT_OK


# ---------------------------------------------------------------------------
# Parsing: what must be understood, and what must fail loudly
# ---------------------------------------------------------------------------


def test_hash_continuations_comments_and_markers_are_parsed(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    write(
        root,
        "environments/requirements.lock",
        "# This file was autogenerated by uv\n"
        "#    uv pip compile x.in --output-file y {}\n".format(BACKSLASH)
        + "#      --generate-hashes\n"
        + "absl-py==2.5.0 {}\n".format(BACKSLASH)
        + "    --hash=sha256:{} {}\n".format("0" * 64, BACKSLASH)
        + "    --hash=sha256:{}\n".format("1" * 64)
        + "    # via keras\n"
        + '\nnvidia-nccl-cu12==2.30.7 ; platform_system == "Linux"\n'
        + "cachecontrol[filecache]==0.14.4\n",
    )
    write(root, "requirements.txt", "absl-py==2.5.0\nnvidia_nccl_cu12==2.30.7\ncachecontrol==0.14.4\n")
    code, report = run_gate(root)
    assert code == gate.EXIT_OK
    assert report["locked_distribution_count"] == 3


def test_comment_ending_in_backslash_does_not_continue(tmp_path):
    """The CI render manifest header has exactly this shape.

    If a comment were allowed to continue, the following comment line would be
    swallowed and a documentation line could be read as a requirement.
    """
    text = (
        "#   pip download nbclient==1 ipykernel==2 -d /tmp/pkgs {}\n".format(BACKSLASH)
        + "#     --python-version 3.13 --only-binary :all: {}\n".format(BACKSLASH)
        + "#     --platform manylinux_2_17_x86_64\n"
        + "asttokens==3.0.2\n"
    )
    lines = gate.logical_lines(text)
    assert lines == [(4, "asttokens==3.0.2")]


def test_multiple_hash_continuation_lines_collapse_to_one_requirement():
    """Four physical lines (pin, two hashes, a trailing 'via' comment) -> one logical line."""
    text = pinned("aiohttp", "3.14.3", hashed=True)
    lines = gate.logical_lines(text)
    assert len(lines) == 1, lines
    assert lines[0][0] == 1
    assert lines[0][1].startswith("aiohttp==3.14.3")
    req = gate.parse_requirement_line("f", lines[0][0], lines[0][1])
    assert req is not None and req.normalized == "aiohttp"


@pytest.mark.parametrize(
    "tail_form,expected",
    [
        ("alpha", "alpha"),
        ("alpha==1.0.0", "alpha"),
        ("alpha >= 1.0.0", "alpha"),
        ("alpha!=1.2,>=1.0", "alpha"),
        ("alpha[extra]==1.0.0", "alpha"),
        ("alpha @ https://example.invalid/alpha.whl", "alpha"),
        ('alpha==1.0.0 ; python_version < "3.11"', "alpha"),
    ],
)
def test_specifier_forms_this_repo_contains_are_understood(tail_form, expected):
    req = gate.parse_requirement_line("f", 1, tail_form)
    assert req is not None and req.normalized == expected


@pytest.mark.parametrize(
    "line",
    [
        "--index-url https://example.invalid/simple",
        "--extra-index-url https://example.invalid/simple",
        "--find-links ./wheels",
        "--no-binary :all:",
        "--only-binary :all:",
        "--require-hashes",
        "--prefer-binary",
        "-i https://example.invalid/simple",
    ],
)
def test_recognised_options_carry_no_distribution(line):
    assert gate.parse_requirement_line("f", 1, line) is None


@pytest.mark.parametrize(
    "line",
    [
        "https://example.invalid/pkg-1.0-py3-none-any.whl",
        "./local/wheelhouse/pkg-1.0.whl",
        "--wat-is-this foo",
        "-z something",
        "alpha 1.0.0",
        "alpha == 1.0.0 extra junk here",
        # Two requirements on one line: reading only the first would silently
        # drop the second, which is a package this gate then fails to monitor.
        "alpha==1.0.0 beta==2.0.0",
    ],
)
def test_unclassifiable_line_raises_rather_than_being_skipped(line):
    with pytest.raises(gate.ManifestParseError):
        gate.parse_requirement_line("f", 7, line)


def test_a_second_requirement_on_one_line_is_never_silently_dropped(tmp_path):
    """End to end: the half-read line must stop the gate, not shrink its scope."""
    root = make_repo(tmp_path, lock_names=["alpha"], manifest_names=["alpha"], hashed=False)
    write(root, "environments/requirements.lock", "alpha==1.0.0 beta==2.0.0\n")
    code, report = run_gate(root)
    assert code == gate.EXIT_COULD_NOT_RUN
    assert report["status"] != "ok"


def test_unparseable_lock_line_exits_could_not_run_not_clean(tmp_path):
    """A line the parser cannot classify is a package it does not monitor.

    It must never come back as a clean pass.
    """
    root = make_repo(tmp_path, lock_names=["alpha"], manifest_names=["alpha"], hashed=False)
    write(
        root,
        "environments/requirements.lock",
        "alpha==1.0.0\nhttps://example.invalid/beta-1.0-py3-none-any.whl\n",
    )
    code, report = run_gate(root)
    assert code == gate.EXIT_COULD_NOT_RUN
    assert report["status"] == "could_not_run"
    assert "line 2" in report["error"]
    text = gate.render(report, code)
    assert "COULD NOT RUN" in text
    assert "certified NOTHING" in text


def test_unparseable_manifest_line_exits_could_not_run(tmp_path):
    """A manifest the tool cannot read must not be silently treated as empty.

    Silently empty would understate coverage and cause a false FINDING, which
    trains readers to ignore the gate.
    """
    root = make_repo(tmp_path, lock_names=["alpha"], manifest_names=["alpha"], hashed=False)
    write(root, "requirements.txt", "alpha==1.0.0\n-z nonsense\n")
    code, report = run_gate(root)
    assert code == gate.EXIT_COULD_NOT_RUN
    assert "unparseable line in a parsed manifest" in report["error"]


# ---------------------------------------------------------------------------
# Could-not-run must be visibly different from clean
# ---------------------------------------------------------------------------


def test_missing_lock_exits_two_not_zero(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "requirements.txt", "alpha==1.0.0\n")
    code, report = run_gate(root)
    assert code == gate.EXIT_COULD_NOT_RUN
    assert code != gate.EXIT_OK
    assert "not found" in report["error"]
    assert "COULD NOT RUN" in gate.render(report, code)


def test_empty_lock_exits_two_not_zero(tmp_path):
    """An empty lock trivially has nothing uncovered. That is not a pass."""
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", "# nothing here\n\n")
    write(root, "requirements.txt", "alpha==1.0.0\n")
    code, report = run_gate(root)
    assert code == gate.EXIT_COULD_NOT_RUN
    assert "declares no distributions" in report["error"]


def test_no_parsed_manifest_at_all_exits_two_not_one(tmp_path):
    """Nothing to compare against is a broken input, not 148 findings."""
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", pinned("alpha"))
    code, report = run_gate(root)
    assert code == gate.EXIT_COULD_NOT_RUN
    assert "no GitHub-parsed manifest" in report["error"]


def test_the_three_exit_codes_are_distinct():
    assert len({gate.EXIT_OK, gate.EXIT_FINDINGS, gate.EXIT_COULD_NOT_RUN}) == 3
    assert (gate.EXIT_OK, gate.EXIT_FINDINGS, gate.EXIT_COULD_NOT_RUN) == (0, 1, 2)


# ---------------------------------------------------------------------------
# The parsed-manifest filename rule
# ---------------------------------------------------------------------------


def test_parsed_manifest_rule_matches_txt_and_pyproject():
    files = frozenset({"pyproject.toml", "requirements.txt", "environments/requirements-ci.txt"})
    assert gate.is_parsed_manifest("pyproject.toml", files)
    assert gate.is_parsed_manifest("requirements.txt", files)
    assert gate.is_parsed_manifest("environments/requirements-ci.txt", files)


def test_parsed_manifest_rule_rejects_the_lock_and_conda_files():
    files = frozenset({"environments/requirements.lock", "environment.yml", "environments/predig.yaml"})
    assert not gate.is_parsed_manifest("environments/requirements.lock", files)
    assert not gate.is_parsed_manifest("environment.yml", files)
    assert not gate.is_parsed_manifest("environments/predig.yaml", files)


def test_dot_in_file_is_parsed_only_without_a_compiled_txt_sibling():
    """The measured 10-of-10 fit: only requirements-lock.in has no .txt sibling."""
    files = frozenset(
        {
            "environments/requirements-lock.in",
            "environments/requirements.lock",
            "environments/requirements-ci.in",
            "environments/requirements-ci.txt",
            "requirements.in",
            "requirements.txt",
        }
    )
    assert gate.is_parsed_manifest("environments/requirements-lock.in", files)
    assert not gate.is_parsed_manifest("environments/requirements-ci.in", files)
    assert not gate.is_parsed_manifest("requirements.in", files)


def test_nested_pyproject_is_not_treated_as_the_root_manifest():
    files = frozenset({"pyproject.toml", "vendor/pkg/pyproject.toml"})
    assert gate.is_parsed_manifest("pyproject.toml", files)
    assert not gate.is_parsed_manifest("vendor/pkg/pyproject.toml", files)


def test_duplicate_checkouts_and_vendored_trees_are_never_credited():
    """A requirements file inside a worktree sits on ANOTHER branch.

    Crediting it would certify coverage from code that is not on this branch.
    """
    files = frozenset(
        {
            ".claude/worktrees/feat-x/requirements.txt",
            "_local/vendor/requirements.txt",
            ".venv/Lib/site-packages/foo/requirements.txt",
            "requirements.txt",
        }
    )
    assert gate.is_parsed_manifest("requirements.txt", files)
    assert not gate.is_parsed_manifest(".claude/worktrees/feat-x/requirements.txt", files)
    assert not gate.is_parsed_manifest("_local/vendor/requirements.txt", files)
    assert not gate.is_parsed_manifest(".venv/Lib/site-packages/foo/requirements.txt", files)


def test_discovery_finds_manifests_by_pattern_not_by_a_hardcoded_list(tmp_path):
    """A newly added requirements file must be picked up with no code change."""
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", pinned("alpha"))
    write(root, "requirements.txt", pinned("alpha"))
    before = gate.discover_parsed_manifests(root)
    write(root, "environments/requirements-brand-new.txt", pinned("beta"))
    after = gate.discover_parsed_manifests(root)
    assert set(after) - set(before) == {"environments/requirements-brand-new.txt"}


def test_a_new_lock_only_package_is_caught_by_discovery(tmp_path):
    """The scenario the gate was built for, end to end."""
    root = make_repo(tmp_path, lock_names=["alpha"], manifest_names=["alpha"])
    assert run_gate(root)[0] == gate.EXIT_OK
    lock = root / "environments/requirements.lock"
    lock.write_text(lock.read_text(encoding="utf-8") + pinned("future-lock-only-dep", hashed=True), encoding="utf-8")
    code, report = run_gate(root)
    assert code == gate.EXIT_FINDINGS
    assert [item["name"] for item in report["uncovered"]] == ["future-lock-only-dep"]


# ---------------------------------------------------------------------------
# Includes
# ---------------------------------------------------------------------------


def test_includes_are_not_credited_by_default(tmp_path):
    """Whether GitHub resolves -r includes is unmeasured, so do not assume it."""
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", pinned("alpha"))
    write(root, "environments/requirements-lock.in", "-r ../base.in\n")
    write(root, "base.in", pinned("alpha"))
    code, report = run_gate(root)
    assert code == gate.EXIT_FINDINGS
    assert any("include not followed" in note for note in report["notes"])


def test_includes_are_credited_when_asked(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    write(root, "environments/requirements.lock", pinned("alpha"))
    write(root, "environments/requirements-lock.in", "-r ../base.in\n")
    write(root, "base.in", pinned("alpha"))
    code, _ = gate.run(root, "environments/requirements.lock", True)
    assert code == gate.EXIT_OK


def test_constraint_include_is_recognised_not_misread_as_a_package():
    assert gate.parse_requirement_line("f", 1, "-c constraints.txt") is None
    assert gate.parse_requirement_line("f", 1, "--constraint constraints.txt") is None


# ---------------------------------------------------------------------------
# CLI surface
# ---------------------------------------------------------------------------


def test_json_output_is_valid_and_carries_the_findings(tmp_path, capsys):
    root = make_repo(tmp_path, lock_names=["alpha", "orphan-pkg"], manifest_names=["alpha"])
    code = gate.main(["--repo-root", str(root), "--json"])
    payload = json.loads(capsys.readouterr().out)
    assert code == gate.EXIT_FINDINGS
    assert payload["status"] == "findings"
    assert payload["uncovered"][0]["name"] == "orphan-pkg"
    assert payload["parsed_manifest_rule_measured"] == gate.PARSED_MANIFEST_RULE_MEASURED


def test_cli_exit_code_is_the_process_exit_code(tmp_path):
    root = make_repo(tmp_path, lock_names=["alpha", "orphan-pkg"], manifest_names=["alpha"])
    proc = subprocess.run(
        [sys.executable, str(MODULE_PATH), "--repo-root", str(root)],
        capture_output=True,
        check=False,
    )
    assert proc.returncode == gate.EXIT_FINDINGS
    assert b"orphan-pkg" in proc.stdout


def test_report_names_the_tree_it_certified(tmp_path):
    """Rule 9 of the git-instruments set: say WHICH checkout was measured."""
    root = make_repo(tmp_path, lock_names=["alpha"], manifest_names=["alpha"])
    code, report = run_gate(root)
    assert str(root) in gate.render(report, code)


# ---------------------------------------------------------------------------
# The live repository
# ---------------------------------------------------------------------------


def test_live_repo_lock_is_fully_covered():
    """The invariant this gate enforces, asserted against the real checkout."""
    if not (REPO_ROOT / gate.DEFAULT_LOCK).is_file():
        pytest.skip("lock file absent from this checkout")
    code, report = gate.run(REPO_ROOT, gate.DEFAULT_LOCK, False)
    assert report["uncovered"] == [], gate.render(report, code)
    assert code == gate.EXIT_OK
    assert report["locked_distribution_count"] > 100
    assert report["covered_count"] == report["locked_distribution_count"]


def test_live_repo_discovery_reproduces_the_measured_manifest_set():
    """The hardcoded filename rule must still reproduce the calibration.

    Measured against the live dependency graph on the date recorded in the
    tool. If this list drifts, re-run the calibration query in the tool's
    header before changing either side.
    """
    if not (REPO_ROOT / gate.DEFAULT_LOCK).is_file():
        pytest.skip("not the SESTRAV checkout")
    measured = {
        "pyproject.toml",
        "requirements.txt",
        "environments/requirements-ci-build.txt",
        "environments/requirements-ci-mypy.txt",
        "environments/requirements-ci-pytest-cov.txt",
        "environments/requirements-ci-render.txt",
        "environments/requirements-ci-ruff.txt",
        "environments/requirements-ci-torch-cpu.txt",
        "environments/requirements-ci.txt",
        "environments/requirements-pip-audit.txt",
        "environments/requirements-pip-bootstrap.txt",
        "environments/requirements-sbom.txt",
        "environments/requirements-security.txt",
        "environments/requirements-semgrep.txt",
        "environments/requirements-lock.in",
    }
    derived = set(gate.discover_parsed_manifests(REPO_ROOT))
    assert derived == measured, "derived-only={} measured-only={}".format(
        sorted(derived - measured), sorted(measured - derived)
    )
