"""Regression tests for tools/check_lockfile_freshness.py.

The CI gate this script backs (.github/workflows/dependency-lockfile-check.yml)
must fail closed on a dependency-bump PR whose .in source drifted from its
compiled, hash-pinned output. These tests exercise the parsing/comparison
logic directly against temp fixtures so they do not depend on the live state
of the repo's own requirements*.in/.txt files.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import textwrap

import pytest

from tools import check_lockfile_freshness as freshness
from tools.check_lockfile_freshness import (
    check_pair,
    discover_unmapped_in_files,
    normalize,
    parse_compiled_file,
    parse_in_file,
)


def _write(path, content):
    path.write_text(textwrap.dedent(content), encoding="utf-8")
    return path


def test_normalize_pep503():
    assert normalize("Foo_Bar.Baz") == "foo-bar-baz"
    assert normalize("requests") == "requests"


def test_parse_in_file_reads_exact_and_floor_pins(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        """\
        # comment
        biopython==1.87
        cryptography>=48.0.1
        """,
    )
    pins = parse_in_file(in_file)
    assert pins["biopython"].operator == "=="
    assert pins["biopython"].version == "1.87"
    assert pins["cryptography"].operator == ">="
    assert pins["cryptography"].version == "48.0.1"


def test_parse_in_file_follows_includes(tmp_path):
    base = _write(tmp_path / "base.in", "numpy==2.4.6\n")
    top = _write(tmp_path / "top.in", "-r base.in\npandas==3.0.3\n")
    pins = parse_in_file(top)
    assert "numpy" in pins
    assert "pandas" in pins


def test_parse_in_file_marks_environment_markers(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"\n',
    )
    pins = parse_in_file(in_file)
    assert pins["nvidia-nccl-cu12"].marker is True


def test_parse_compiled_file_detects_hash_presence(tmp_path):
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        #
        # autogenerated
        #
        biopython==1.87 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        numpy==2.4.6
        """,
    )
    entries = parse_compiled_file(out_file)
    assert entries["biopython"].has_hash is True
    assert entries["numpy"].has_hash is False


def test_check_pair_clean_when_in_sync(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        biopython==1.87 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    assert check_pair(in_file, out_file) == []


def test_check_pair_flags_stale_version(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "bandit==1.9.5\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        bandit==1.9.4 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1
    assert "bandit==1.9.5" in problems[0]
    assert "bandit==1.9.4" in problems[0]
    assert "stale" in problems[0]


def test_check_pair_flags_missing_package(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "shap==0.51.0\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87\n")
    problems = check_pair(in_file, out_file)
    assert any("missing from the compiled output" in p for p in problems)


def test_check_pair_flags_unhashed_entry(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87\n")
    problems = check_pair(in_file, out_file)
    assert any("unhashed" in p for p in problems)


def test_check_pair_flags_floor_violation(tmp_path):
    in_file = _write(tmp_path / "requirements-lock.in", "aiohttp>=3.14.2\n")
    out_file = _write(
        tmp_path / "requirements.lock",
        """\
        aiohttp==3.14.1 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    problems = check_pair(in_file, out_file)
    assert any("below floor" in p for p in problems)


def test_check_pair_allows_marker_pin_to_be_absent(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"\n',
    )
    out_file = _write(tmp_path / "requirements.txt", "")
    assert check_pair(in_file, out_file) == []


def test_check_pair_missing_compiled_output(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    missing_out = tmp_path / "requirements.txt"
    problems = check_pair(in_file, missing_out)
    assert len(problems) == 1
    assert "compiled output is missing" in problems[0]


def test_discover_unmapped_in_files_is_empty_for_real_repo():
    # The live LOCKFILE_PAIRS mapping in the script must cover every
    # requirements*.in file actually tracked in this repo - this is the
    # fail-closed guard described in the module docstring.
    from tools.check_lockfile_freshness import LOCKFILE_PAIRS

    mapped = {pair[0] for pair in LOCKFILE_PAIRS}
    unmapped = discover_unmapped_in_files(mapped)
    assert unmapped == [], f"unmapped requirements*.in files: {unmapped}"


def _init_repo_with_ignored_copy(root):
    """Build a temp git repo whose .gitignore hides a nested repo copy.

    Mirrors the real layout that broke this check: gitignored full copies of
    the repo (agent worktrees under .claude/) leave their requirements*.in
    files visible to a filesystem walk.

    The copy is planted under vendor/ rather than .claude/ on purpose. .claude
    is in the fallback walk's denylist, so a .claude fixture would be filtered
    out by *either* code path and the test would still pass if the git path
    silently stopped working. vendor/ is unknown to the denylist, so only real
    gitignore awareness can satisfy the assertion.
    """
    _write(root / ".gitignore", "vendor/\n")
    _write(root / "requirements.in", "biopython==1.87\n")
    (root / "environments").mkdir()
    _write(root / "environments" / "requirements-ci.in", "ruff==0.16.0\n")

    ignored = root / "vendor" / "nested-copy" / "environments"
    ignored.mkdir(parents=True)
    _write(ignored / "requirements-ci.in", "ruff==0.16.0\n")
    _write(ignored.parent / "requirements.in", "biopython==1.87\n")

    env = {**os.environ, "GIT_CONFIG_GLOBAL": str(root / "gitconfig"), "GIT_CONFIG_SYSTEM": ""}
    for command in (["git", "init", "-q"], ["git", "add", "-A"]):
        subprocess.run(command, cwd=root, env=env, check=True, capture_output=True)


def test_discover_ignores_gitignored_nested_repo_copy(tmp_path, monkeypatch):
    """A gitignored copy of the repo must not produce unmapped-file errors.

    Regression: discovery used to rglob the filesystem with a hand-maintained
    directory denylist that omitted .claude/, so each agent worktree on a
    developer's disk contributed ~10 phantom failures and exit 1, while CI
    passed because a clean checkout has no such copies.

    The fixture hides the copy under vendor/, which the fallback walk's
    denylist does not know about, so this fails if the git path stops working
    rather than passing on the fallback by coincidence.
    """
    if shutil.which("git") is None:
        pytest.skip("git not available")
    _init_repo_with_ignored_copy(tmp_path)
    monkeypatch.setattr(freshness, "REPO_ROOT", tmp_path)

    assert freshness._git_tracked_in_files() is not None, "git path must be live"

    unmapped = discover_unmapped_in_files({"requirements.in"})

    assert unmapped == ["environments/requirements-ci.in"]
    assert not [rel for rel in unmapped if "vendor" in rel]


def test_discover_falls_back_to_filesystem_walk_without_git(tmp_path, monkeypatch):
    """Without git the walk still runs, and still skips the known copy dirs."""
    _write(tmp_path / "requirements.in", "biopython==1.87\n")
    ignored = tmp_path / ".claude" / "worktrees" / "agent-deadbeef"
    ignored.mkdir(parents=True)
    _write(ignored / "requirements.in", "biopython==1.87\n")

    monkeypatch.setattr(freshness, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(freshness, "_git_tracked_in_files", lambda: None)

    assert discover_unmapped_in_files(set()) == ["requirements.in"]


@pytest.mark.smoke
def test_current_repo_hash_completeness_for_all_pairs():
    """Every mapped pair in this repo must report zero problems.

    This pins the true-negative behavior of the checker against real repo
    data. requirements.txt and environments/requirements.lock used to be
    excluded here because they carried accumulated drift from several
    Dependabot .in bumps; PR #177's relock cleared it, so the exclusion is
    retired and all 10 pairs are covered. Driving this off LOCKFILE_PAIRS
    rather than a hand-copied list means a newly mapped pair is covered
    automatically instead of silently escaping the check.
    """
    from tools.check_lockfile_freshness import LOCKFILE_PAIRS, REPO_ROOT

    for in_rel, out_rel in LOCKFILE_PAIRS:
        problems = check_pair(REPO_ROOT / in_rel, REPO_ROOT / out_rel)
        assert problems == [], f"{in_rel} -> {out_rel}: {problems}"
