"""Regression tests for tools/check_lockfile_freshness.py.

The CI gate this script backs (.github/workflows/dependency-lockfile-check.yml)
must fail closed on a dependency-bump PR whose .in source drifted from its
compiled, hash-pinned output. These tests exercise the parsing/comparison
logic directly against temp fixtures so they do not depend on the live state
of the repo's own requirements*.in/.txt files.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import textwrap

import pytest

from tools import check_lockfile_freshness as freshness
from tools.check_lockfile_freshness import (
    check_pair,
    discover_unmapped_in_files,
    normalize,
    parse_compiled_file,
    parse_in_file,
)


def _write(path, content):
    path.write_text(textwrap.dedent(content), encoding="utf-8")
    return path


def test_normalize_pep503():
    assert normalize("Foo_Bar.Baz") == "foo-bar-baz"
    assert normalize("requests") == "requests"


def test_parse_in_file_reads_exact_and_floor_pins(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        """\
        # comment
        biopython==1.87
        cryptography>=48.0.1
        """,
    )
    pins = parse_in_file(in_file)
    assert pins["biopython"].operator == "=="
    assert pins["biopython"].version == "1.87"
    assert pins["cryptography"].operator == ">="
    assert pins["cryptography"].version == "48.0.1"


def test_parse_in_file_follows_includes(tmp_path):
    base = _write(tmp_path / "base.in", "numpy==2.4.6\n")
    top = _write(tmp_path / "top.in", "-r base.in\npandas==3.0.3\n")
    pins = parse_in_file(top)
    assert "numpy" in pins
    assert "pandas" in pins


def test_parse_in_file_marks_environment_markers(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"\n',
    )
    pins = parse_in_file(in_file)
    assert pins["nvidia-nccl-cu12"].marker is True


def test_parse_compiled_file_detects_hash_presence(tmp_path):
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        #
        # autogenerated
        #
        biopython==1.87 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        numpy==2.4.6
        """,
    )
    entries = parse_compiled_file(out_file)
    assert entries["biopython"].has_hash is True
    assert entries["numpy"].has_hash is False


def test_check_pair_clean_when_in_sync(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        biopython==1.87 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    assert check_pair(in_file, out_file) == []


def test_check_pair_flags_stale_version(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "bandit==1.9.5\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        bandit==1.9.4 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1
    assert "bandit==1.9.5" in problems[0]
    assert "bandit==1.9.4" in problems[0]
    assert "stale" in problems[0]


def test_check_pair_flags_missing_package(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "shap==0.51.0\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87\n")
    problems = check_pair(in_file, out_file)
    assert any("missing from the compiled output" in p for p in problems)


def test_check_pair_flags_unhashed_entry(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87\n")
    problems = check_pair(in_file, out_file)
    assert any("unhashed" in p for p in problems)


def test_check_pair_flags_floor_violation(tmp_path):
    in_file = _write(tmp_path / "requirements-lock.in", "aiohttp>=3.14.2\n")
    out_file = _write(
        tmp_path / "requirements.lock",
        """\
        aiohttp==3.14.1 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    problems = check_pair(in_file, out_file)
    assert any("below floor" in p for p in problems)


def test_check_pair_allows_marker_pin_to_be_absent(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"\n',
    )
    out_file = _write(tmp_path / "requirements.txt", "")
    assert check_pair(in_file, out_file) == []


def test_check_pair_missing_compiled_output(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    missing_out = tmp_path / "requirements.txt"
    problems = check_pair(in_file, missing_out)
    assert len(problems) == 1
    assert "compiled output is missing" in problems[0]


# ---------------------------------------------------------------------------
# Inputs the parser cannot read must be reported, never dropped.
#
# Before this block existed, parse_in_file skipped without a word an "-r"
# include whose target did not exist, a pin carrying extras
# (pkg[extra]==1.0), and any line that was not a single == or >= pin (~=, a
# bare name, a pip option). A range or a wildcard was misread rather than
# skipped: the prefix match took "a>=1,<2" as a bare floor and "numpy==2.4.*"
# as version "2.4.". parse_compiled_file likewise dropped a compiled entry
# carrying extras, hiding it from the unhashed check. check_pair compared only
# what was left, so the gate passed while it had stopped reading part of its
# input. Every test below except the last failed on that code.
# ---------------------------------------------------------------------------

_HASHED = "    --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68\n"


def test_check_pair_fails_on_include_that_does_not_resolve(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "-r does-not-exist.in\nbiopython==1.87\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87 \\\n" + _HASHED)
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1, problems
    assert "does-not-exist.in" in problems[0]
    assert "does not resolve to an existing file" in problems[0]
    assert "requirements.in:1:" in problems[0]


def test_check_pair_reports_unresolvable_include_in_a_nested_file(tmp_path):
    _write(tmp_path / "base.in", "-r gone.in\nnumpy==2.4.6\n")
    top = _write(tmp_path / "top.in", "-r base.in\n")
    out_file = _write(tmp_path / "top.txt", "numpy==2.4.6 \\\n" + _HASHED)
    problems = check_pair(top, out_file)
    assert len(problems) == 1, problems
    assert "gone.in" in problems[0]
    assert "base.in:1:" in problems[0]


def test_parse_in_file_raises_without_a_collector(tmp_path):
    """A direct caller must not receive a partial parse silently."""
    in_file = _write(tmp_path / "requirements.in", "-r does-not-exist.in\n")
    with pytest.raises(ValueError, match="does not resolve to an existing file"):
        parse_in_file(in_file)


@pytest.mark.parametrize(
    "line",
    [
        "uvicorn[standard]==0.53.0",
        "uvicorn[standard,socks] >= 0.53.0",
        'uvicorn [standard]==0.53.0 ; python_version >= "3.10"',
    ],
)
def test_parse_in_file_accepts_extras_on_a_pin(tmp_path, line):
    in_file = _write(tmp_path / "requirements.in", line + "\n")
    pins = parse_in_file(in_file)
    assert "uvicorn" in pins, f"extras pin dropped: {line!r}"
    assert pins["uvicorn"].name == "uvicorn"
    assert pins["uvicorn"].version == "0.53.0"
    assert pins["uvicorn"].marker is ("python_version" in line)


def test_check_pair_flags_stale_extras_pin(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "uvicorn[standard]==0.53.0\n")
    out_file = _write(tmp_path / "requirements.txt", "uvicorn==0.40.0 \\\n" + _HASHED)
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1, problems
    assert "uvicorn==0.53.0" in problems[0]
    assert "uvicorn==0.40.0" in problems[0]
    assert "stale" in problems[0]


def test_parse_compiled_file_reads_entries_with_extras(tmp_path):
    # environments/requirements-semgrep.txt (its header says uv generated it)
    # carried one, pyjwt[crypto]==2.13.0, until a uv recompile wrote that pin
    # without the extra. Whether a compiled line keeps its extras depends on the
    # tool and its flags, so the parser must accept them.
    out_file = _write(
        tmp_path / "requirements.txt",
        "pyjwt[crypto]==2.13.0 \\\n" + _HASHED + "shap[plots]==0.51.0\n",
    )
    entries = parse_compiled_file(out_file)
    assert "pyjwt" in entries, f"extras entry dropped: {sorted(entries)}"
    assert entries["pyjwt"].version == "2.13.0"
    assert entries["pyjwt"].has_hash is True
    assert entries["shap"].has_hash is False


def test_check_pair_flags_unhashed_compiled_entry_with_extras(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        "biopython==1.87 \\\n" + _HASHED + "pyjwt[crypto]==2.13.0\n",
    )
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1, problems
    assert "pyjwt==2.13.0" in problems[0]
    assert "unhashed" in problems[0]


@pytest.mark.parametrize(
    "body",
    [
        "pyjwt==2.13.0 \\\n" + _HASHED + "pyjwt[crypto]==2.13.0\n",
        "pyjwt[crypto]==2.13.0\n" + "pyjwt==2.13.0 \\\n" + _HASHED,
    ],
    ids=["hashed-first", "unhashed-first"],
)
def test_check_pair_flags_an_unhashed_duplicate_in_either_order(tmp_path, body):
    # "pyjwt==" and "pyjwt[crypto]==" normalize to one key; the unhashed
    # line must be reported whichever comes last.
    in_file = _write(tmp_path / "requirements.in", "pyjwt==2.13.0\n")
    out_file = _write(tmp_path / "requirements.txt", body)
    assert parse_compiled_file(out_file)["pyjwt"].has_hash is False
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1, problems
    assert "pyjwt==2.13.0" in problems[0]
    assert "unhashed" in problems[0]


@pytest.mark.parametrize(
    ("line", "compiled"),
    [
        # Compatible release: this gate compares with a digit tuple, not a
        # PEP 440 comparator, so it cannot hold ~= to its word.
        ("bandit~=1.9.5", "bandit==1.8.0"),
        # A range: the old prefix match read the floor and dropped the ceiling.
        ("aiohttp>=3.14.3,<3.15", "aiohttp==3.15.0"),
        # A wildcard: the old prefix match read "2.4." as the version.
        ("numpy==2.4.*", "numpy==2.4.6"),
        # A bare name has no version to compare.
        ("requests", "requests==2.32.5"),
        # pip options and constraint files change what the lock resolves to.
        ("--index-url https://example.invalid/simple", None),
        ("-c constraints.txt", None),
    ],
)
def test_check_pair_reports_lines_it_cannot_classify(tmp_path, line, compiled):
    in_file = _write(tmp_path / "requirements.in", f"biopython==1.87\n{line}\n")
    body = "biopython==1.87 \\\n" + _HASHED
    if compiled:
        body += f"{compiled} \\\n" + _HASHED
    out_file = _write(tmp_path / "requirements.txt", body)
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1, problems
    assert "requirements.in:2:" in problems[0]
    assert "cannot classify" in problems[0]
    assert repr(line) in problems[0]


def test_check_pair_reports_every_unreadable_line_not_only_the_first(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        """\
        -r gone.in
        biopython==1.87
        bandit~=1.9.5
        requests
        """,
    )
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87 \\\n" + _HASHED)
    problems = check_pair(in_file, out_file)
    assert len(problems) == 3, problems
    assert "requirements.in:1:" in problems[0]
    assert "requirements.in:3:" in problems[1]
    assert "requirements.in:4:" in problems[2]


def test_parse_in_file_still_strips_an_inline_comment_after_a_pin(tmp_path):
    # Guard for the full-line match above: an inline comment is not an
    # unclassifiable tail. Passes before and after the fix by design. pip
    # starts a comment at a "#" after any whitespace, so a TAB separator
    # counts too; splitting on " #" alone reported the tab line as
    # unclassifiable.
    in_file = _write(
        tmp_path / "requirements.in",
        "biopython==1.87  # pinned for the Bio.Align API\n"
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"  # CUDA only\n'
        "numpy==2.4.6\t# tab-separated comment\n",
    )
    pins = parse_in_file(in_file)
    assert pins["biopython"].version == "1.87"
    assert pins["nvidia-nccl-cu12"].marker is True
    assert pins["numpy"].version == "2.4.6"
    assert pins["numpy"].marker is False


def test_discover_unmapped_in_files_is_empty_for_real_repo():
    # The live LOCKFILE_PAIRS mapping in the script must cover every
    # requirements*.in file actually tracked in this repo - this is the
    # fail-closed guard described in the module docstring.
    from tools.check_lockfile_freshness import LOCKFILE_PAIRS

    mapped = {pair[0] for pair in LOCKFILE_PAIRS}
    unmapped = discover_unmapped_in_files(mapped)
    assert unmapped == [], f"unmapped requirements*.in files: {unmapped}"


def _init_repo_with_ignored_copy(root):
    """Build a temp git repo whose .gitignore hides a nested repo copy.

    Mirrors the real layout that broke this check: gitignored full copies of
    the repo (agent worktrees under .claude/) leave their requirements*.in
    files visible to a filesystem walk.

    The copy is planted under vendor/ rather than .claude/ on purpose. .claude
    is in the fallback walk's denylist, so a .claude fixture would be filtered
    out by *either* code path and the test would still pass if the git path
    silently stopped working. vendor/ is unknown to the denylist, so only real
    gitignore awareness can satisfy the assertion.
    """
    _write(root / ".gitignore", "vendor/\n")
    _write(root / "requirements.in", "biopython==1.87\n")
    (root / "environments").mkdir()
    _write(root / "environments" / "requirements-ci.in", "ruff==0.16.0\n")

    ignored = root / "vendor" / "nested-copy" / "environments"
    ignored.mkdir(parents=True)
    _write(ignored / "requirements-ci.in", "ruff==0.16.0\n")
    _write(ignored.parent / "requirements.in", "biopython==1.87\n")

    # Strip GIT_DIR / GIT_WORK_TREE / GIT_INDEX_FILE: if any were set in the
    # ambient environment, git gives them precedence over cwd-based repo
    # discovery (neither command below passes an explicit -C/--git-dir), so
    # `git init`/`git add -A` would silently target the real repo's .git and
    # index instead of this scratch root. Explicit -C/--git-dir/--work-tree
    # below is a second, independent guard against that same failure mode.
    env = {
        key: value
        for key, value in os.environ.items()
        if key not in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE")
    }
    env["GIT_CONFIG_GLOBAL"] = str(root / "gitconfig")
    env["GIT_CONFIG_SYSTEM"] = ""
    git_dir = str(root / ".git")
    for command in (
        ["git", "-C", str(root), "init", "-q"],
        ["git", f"--git-dir={git_dir}", f"--work-tree={root}", "add", "-A"],
    ):
        subprocess.run(command, cwd=root, env=env, check=True, capture_output=True)


def test_discover_ignores_gitignored_nested_repo_copy(tmp_path, monkeypatch):
    """A gitignored copy of the repo must not produce unmapped-file errors.

    Regression: discovery used to rglob the filesystem with a hand-maintained
    directory denylist that omitted .claude/, so each agent worktree on a
    developer's disk contributed ~10 phantom failures and exit 1, while CI
    passed because a clean checkout has no such copies.

    The fixture hides the copy under vendor/, which the fallback walk's
    denylist does not know about, so this fails if the git path stops working
    rather than passing on the fallback by coincidence.
    """
    if shutil.which("git") is None:
        pytest.skip("git not available")
    _init_repo_with_ignored_copy(tmp_path)
    monkeypatch.setattr(freshness, "REPO_ROOT", tmp_path)

    assert freshness._git_tracked_in_files() is not None, "git path must be live"

    unmapped = discover_unmapped_in_files({"requirements.in"})

    assert unmapped == ["environments/requirements-ci.in"]
    assert not [rel for rel in unmapped if "vendor" in rel]


def test_discover_falls_back_to_filesystem_walk_without_git(tmp_path, monkeypatch):
    """Without git the walk still runs, and still skips the known copy dirs."""
    _write(tmp_path / "requirements.in", "biopython==1.87\n")
    ignored = tmp_path / ".claude" / "worktrees" / "agent-deadbeef"
    ignored.mkdir(parents=True)
    _write(ignored / "requirements.in", "biopython==1.87\n")

    monkeypatch.setattr(freshness, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(freshness, "_git_tracked_in_files", lambda: None)

    assert discover_unmapped_in_files(set()) == ["requirements.in"]


@pytest.mark.smoke
def test_current_repo_hash_completeness_for_all_pairs():
    """Every mapped pair in this repo must report zero problems.

    This pins the true-negative behavior of the checker against real repo
    data. requirements.txt and environments/requirements.lock used to be
    excluded here because they carried accumulated drift from several
    Dependabot .in bumps; PR #177's relock cleared it, so the exclusion is
    retired and every pair in LOCKFILE_PAIRS is covered. No count is stated
    here on purpose: the mapping grows, and `--check` prints the current one.
    Driving this off LOCKFILE_PAIRS rather than a hand-copied list means a
    newly mapped pair is covered automatically instead of silently escaping
    the check.
    """
    from tools.check_lockfile_freshness import LOCKFILE_PAIRS, REPO_ROOT

    for in_rel, out_rel in LOCKFILE_PAIRS:
        problems = check_pair(REPO_ROOT / in_rel, REPO_ROOT / out_rel)
        assert problems == [], f"{in_rel} -> {out_rel}: {problems}"
