"""Regression tests for tools/check_lockfile_freshness.py.

The CI gate this script backs (.github/workflows/dependency-lockfile-check.yml)
must fail closed on a dependency-bump PR whose .in source drifted from its
compiled, hash-pinned output. These tests exercise the parsing/comparison
logic directly against temp fixtures so they do not depend on the live state
of the repo's own requirements*.in/.txt files.
"""

from __future__ import annotations

import textwrap

import pytest

from tools.check_lockfile_freshness import (
    check_pair,
    discover_unmapped_in_files,
    normalize,
    parse_compiled_file,
    parse_in_file,
)


def _write(path, content):
    path.write_text(textwrap.dedent(content), encoding="utf-8")
    return path


def test_normalize_pep503():
    assert normalize("Foo_Bar.Baz") == "foo-bar-baz"
    assert normalize("requests") == "requests"


def test_parse_in_file_reads_exact_and_floor_pins(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        """\
        # comment
        biopython==1.87
        cryptography>=48.0.1
        """,
    )
    pins = parse_in_file(in_file)
    assert pins["biopython"].operator == "=="
    assert pins["biopython"].version == "1.87"
    assert pins["cryptography"].operator == ">="
    assert pins["cryptography"].version == "48.0.1"


def test_parse_in_file_follows_includes(tmp_path):
    base = _write(tmp_path / "base.in", "numpy==2.4.6\n")
    top = _write(tmp_path / "top.in", "-r base.in\npandas==3.0.3\n")
    pins = parse_in_file(top)
    assert "numpy" in pins
    assert "pandas" in pins


def test_parse_in_file_marks_environment_markers(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"\n',
    )
    pins = parse_in_file(in_file)
    assert pins["nvidia-nccl-cu12"].marker is True


def test_parse_compiled_file_detects_hash_presence(tmp_path):
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        #
        # autogenerated
        #
        biopython==1.87 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        numpy==2.4.6
        """,
    )
    entries = parse_compiled_file(out_file)
    assert entries["biopython"].has_hash is True
    assert entries["numpy"].has_hash is False


def test_check_pair_clean_when_in_sync(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        biopython==1.87 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    assert check_pair(in_file, out_file) == []


def test_check_pair_flags_stale_version(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "bandit==1.9.5\n")
    out_file = _write(
        tmp_path / "requirements.txt",
        """\
        bandit==1.9.4 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    problems = check_pair(in_file, out_file)
    assert len(problems) == 1
    assert "bandit==1.9.5" in problems[0]
    assert "bandit==1.9.4" in problems[0]
    assert "stale" in problems[0]


def test_check_pair_flags_missing_package(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "shap==0.51.0\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87\n")
    problems = check_pair(in_file, out_file)
    assert any("missing from the compiled output" in p for p in problems)


def test_check_pair_flags_unhashed_entry(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    out_file = _write(tmp_path / "requirements.txt", "biopython==1.87\n")
    problems = check_pair(in_file, out_file)
    assert any("unhashed" in p for p in problems)


def test_check_pair_flags_floor_violation(tmp_path):
    in_file = _write(tmp_path / "requirements-lock.in", "aiohttp>=3.14.2\n")
    out_file = _write(
        tmp_path / "requirements.lock",
        """\
        aiohttp==3.14.1 \\
            --hash=sha256:a53b324a331d807ab68d442bc777a9de1894d82e6fff082cdeae5b5e4355bd68
        """,
    )
    problems = check_pair(in_file, out_file)
    assert any("below floor" in p for p in problems)


def test_check_pair_allows_marker_pin_to_be_absent(tmp_path):
    in_file = _write(
        tmp_path / "requirements.in",
        'nvidia-nccl-cu12==2.30.7; platform_system == "Linux"\n',
    )
    out_file = _write(tmp_path / "requirements.txt", "")
    assert check_pair(in_file, out_file) == []


def test_check_pair_missing_compiled_output(tmp_path):
    in_file = _write(tmp_path / "requirements.in", "biopython==1.87\n")
    missing_out = tmp_path / "requirements.txt"
    problems = check_pair(in_file, missing_out)
    assert len(problems) == 1
    assert "compiled output is missing" in problems[0]


def test_discover_unmapped_in_files_is_empty_for_real_repo():
    # The live LOCKFILE_PAIRS mapping in the script must cover every
    # requirements*.in file actually tracked in this repo - this is the
    # fail-closed guard described in the module docstring.
    from tools.check_lockfile_freshness import LOCKFILE_PAIRS

    mapped = {pair[0] for pair in LOCKFILE_PAIRS}
    unmapped = discover_unmapped_in_files(mapped)
    assert unmapped == [], f"unmapped requirements*.in files: {unmapped}"


@pytest.mark.smoke
def test_current_repo_hash_completeness_for_known_clean_pairs():
    """The pairs known not to be affected by the pre-existing staleness on
    main (see _local/notes session log) must report zero problems. This
    pins the true-negative behavior of the checker against real repo data,
    independent of the separately-tracked matplotlib/hypothesis/fastapi/etc.
    drift in requirements.txt and environments/requirements.lock.
    """
    from tools.check_lockfile_freshness import REPO_ROOT

    clean_pairs = [
        ("environments/requirements-ci.in", "environments/requirements-ci.txt"),
        ("environments/requirements-ci-build.in", "environments/requirements-ci-build.txt"),
        ("environments/requirements-ci-mypy.in", "environments/requirements-ci-mypy.txt"),
        (
            "environments/requirements-ci-pytest-cov.in",
            "environments/requirements-ci-pytest-cov.txt",
        ),
        ("environments/requirements-ci-ruff.in", "environments/requirements-ci-ruff.txt"),
        ("environments/requirements-pip-audit.in", "environments/requirements-pip-audit.txt"),
        ("environments/requirements-security.in", "environments/requirements-security.txt"),
        ("environments/requirements-semgrep.in", "environments/requirements-semgrep.txt"),
    ]
    for in_rel, out_rel in clean_pairs:
        problems = check_pair(REPO_ROOT / in_rel, REPO_ROOT / out_rel)
        assert problems == [], f"{in_rel} -> {out_rel}: {problems}"
