"""
SESTRAV Output Standardization Script.
Merges output files from all predictors (SESTRAV RF, PRIME, PredIG, and MHC binding) into the canonical schema.
"""
import os
import argparse
import pandas as pd
import numpy as np

def main():
    parser = argparse.ArgumentParser(description="Standardize and merge predictor outputs")
    parser.add_argument("--binding", required=True, help="Path to binding CSV")
    parser.add_argument("--prime", required=True, help="Path to PRIME raw txt")
    parser.add_argument("--predig", required=True, help="Path to PredIG raw CSV")
    parser.add_argument("--sestrav", required=True, help="Path to SESTRAV ranked CSV")
    parser.add_argument("--output", required=True, help="Path to save standardized CSV")
    args = parser.parse_args()
    
    print("[standardize] Starting standardization and merge...")
    
    # 1. Load MHC Binding data
    # Standard format: peptide, and allele columns (or affinity/presentation_score)
    bind_df = pd.read_csv(args.binding)
    print(f"[standardize] Loaded binding data: {len(bind_df)} rows")
    
    # We want a row per peptide-allele pair.
    # Check if the binding data is already in peptide-allele format
    # In SESTRAV, results/{proteome_id}_binding.csv is typically generated by stage2.py
    # Let's see if we need to melt it or if it is already melted.
    # Standard columns of results/{proteome_id}_binding.csv: peptide, allele, affinity, presentation_score, etc.
    # If it is wide format (columns: peptide, HLA-A*02:01, etc.), we melt it.
    if 'allele' not in bind_df.columns:
        # Wide format
        hla_cols = [c for c in bind_df.columns if c.startswith("HLA-") or c.startswith("bind_")]
        if hla_cols:
            bind_df = bind_df.melt(id_vars=['peptide'], value_vars=hla_cols, var_name='hla', value_name='binding_ic50')
        else:
            raise ValueError(f"Binding CSV format not recognized. Columns: {list(bind_df.columns)}")
    else:
        # Already has peptide and allele/hla
        # Rename allele column to hla if present
        bind_df = bind_df.rename(columns={'allele': 'hla', 'affinity': 'binding_ic50'})
        
    # Standardize hla nomenclature
    from src.iedb_data_loader import standardize_allele
    bind_df['hla'] = bind_df['hla'].apply(standardize_allele)
    
    # Ensure peptide is uppercase
    bind_df['peptide'] = bind_df['peptide'].astype(str).str.strip().str.upper()
    
    # Remove duplicates
    bind_df = bind_df.drop_duplicates(subset=['peptide', 'hla']).reset_index(drop=True)
    
    # 2. Load PRIME predictions
    # Columns typically: peptide, MixMHCpred_score, PRIME_score, pctrank
    # Since PRIME output may be per-peptide only (meaning max across alleles is calculated internally),
    # or per-peptide-allele. If it has a hla/allele column, we merge by both, otherwise we merge by peptide.
    prime_df = pd.read_csv(args.prime, sep="\t", comment="#")
    
    # Rename columns fuzzy
    prime_rename = {}
    for col in prime_df.columns:
        cl = str(col).lower().strip()
        if cl in ('peptide', 'sequence'):
            prime_rename[col] = 'peptide'
        elif cl in ('hla', 'allele', 'mhc'):
            prime_rename[col] = 'hla'
        elif cl in ('prime_score', 'score'):
            prime_rename[col] = 'prime_score'
            
    prime_df = prime_df.rename(columns=prime_rename)
    prime_df['peptide'] = prime_df['peptide'].astype(str).str.strip().str.upper()
    if 'hla' in prime_df.columns:
        prime_df['hla'] = prime_df['hla'].apply(standardize_allele)
        prime_df = prime_df.drop_duplicates(subset=['peptide', 'hla'])
    else:
        prime_df = prime_df.drop_duplicates(subset=['peptide'])
        
    # 3. Load PredIG predictions
    # Columns typically: peptide/epitope, allele/HLA_allele, predig_score
    predig_df = pd.read_csv(args.predig)
    predig_rename = {}
    for col in predig_df.columns:
        cl = str(col).lower().strip()
        if cl in ('peptide', 'epitope', 'sequence'):
            predig_rename[col] = 'peptide'
        elif cl in ('hla', 'allele', 'hla_allele'):
            predig_rename[col] = 'hla'
        elif cl in ('predig_score', 'score'):
            predig_rename[col] = 'predig_score'
            
    predig_df = predig_df.rename(columns=predig_rename)
    predig_df['peptide'] = predig_df['peptide'].astype(str).str.strip().str.upper()
    predig_df['hla'] = predig_df['hla'].apply(standardize_allele)
    predig_df = predig_df.drop_duplicates(subset=['peptide', 'hla'])
    
    # 4. Load SESTRAV predictions
    # Columns: peptide, rank, immunogenicity_score
    sestrav_df = pd.read_csv(args.sestrav)
    sestrav_rename = {}
    for col in sestrav_df.columns:
        cl = str(col).lower().strip()
        if cl in ('peptide', 'sequence'):
            sestrav_rename[col] = 'peptide'
        elif cl in ('sestrav_score', 'score', 'immunogenicity_score'):
            sestrav_rename[col] = 'sestrav_score'
            
    sestrav_df = sestrav_df.rename(columns=sestrav_rename)
    sestrav_df['peptide'] = sestrav_df['peptide'].astype(str).str.strip().str.upper()
    sestrav_df = sestrav_df.drop_duplicates(subset=['peptide'])
    
    # 5. Merge all DataFrames
    # Start with bind_df as the spine
    merged = bind_df
    
    # Merge PRIME
    if 'hla' in prime_df.columns:
        merged = merged.merge(prime_df[['peptide', 'hla', 'prime_score']], on=['peptide', 'hla'], how='left')
    else:
        # Broadcast peptide score to all HLA alleles of that peptide
        merged = merged.merge(prime_df[['peptide', 'prime_score']], on='peptide', how='left')
        
    # Merge PredIG
    merged = merged.merge(predig_df[['peptide', 'hla', 'predig_score']], on=['peptide', 'hla'], how='left')
    
    # Merge SESTRAV
    # SESTRAV outputs one score per peptide (since it integrates over binding)
    merged = merged.merge(sestrav_df[['peptide', 'sestrav_score']], on='peptide', how='left')
    
    # Add optional benchmark metadata columns
    # assay_type and hard_negative_flag are not populated for proteomes, so default to NaN
    merged['assay_type'] = np.nan
    merged['hard_negative_flag'] = np.nan
    
    # Reorder columns to match canonical schema
    cols = ['peptide', 'hla', 'binding_ic50', 'prime_score', 'predig_score', 'sestrav_score', 'assay_type', 'hard_negative_flag']
    # Ensure all columns exist in case some merge failed
    for col in cols:
        if col not in merged.columns:
            merged[col] = np.nan
            
    merged = merged[cols]
    
    # Save output
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    merged.to_csv(args.output, index=False)
    print(f"[standardize] Successfully wrote standardized CSV ({len(merged)} rows) to {args.output}")

if __name__ == "__main__":
    main()
