#!/usr/bin/env python
"""Fail-closed check that the committed SBOM artifacts match a freshly generated one.

`docs/sbom.json` and `docs/DEPENDENCY_LICENSES.md` are `pip-licenses` output committed
into the repo. Nothing regenerated them on a schedule and nothing compared them against
the lockfiles, so they drifted silently: as of 2026-08-05 they were last generated
2026-06-26 and **46 of the 124 packages they share with `environments/requirements.lock`
disagreed with it**. Four of those disagreed in the security-relevant direction - the
committed artifacts advertised `torch 2.12.0`, `cryptography 48.0.0`, `gitpython 3.1.46`
and `aiohttp 3.13.5` when the repo already pinned `2.13.0`, `50.0.0`, `3.1.57` and
`3.14.3` respectively. A supply-chain artifact that understates its own project's
posture is worse than no artifact, because downstream tooling parses it as authoritative.

This compares the artifacts CI has just generated from the pinned lockfile against the
copies committed under `docs/`, and fails when they disagree.

Three classes of difference, treated differently on purpose:

1. **Version disagreement** on a package in both artifacts -> FAIL. This is the drift the
   gate was built for.
2. **Present in generated, absent from committed** -> FAIL. The committed SBOM omits a
   package the production install actually produced, so it under-reports the dependency
   set. This also covers the tampering case: an earlier revision of this tool compared
   only the intersection, which meant deleting a package's row outright from
   `docs/sbom.json` passed green as "in sync" - verified by deleting the `torch`,
   `cryptography`, `gitpython` and `aiohttp` rows and watching it exit 0. Silent deletion
   is the strongest form of the "understates its own posture" failure this gate exists to
   prevent, so it must fail, not merely be noted.
3. **Present in committed, absent from generated** -> NOTICE only. The `python-sbom` job
   installs the lockfile with `continue-on-error` because platform-specific wheels (CUDA
   and similar) legitimately fail to install on a GitHub runner, so the generated set is a
   runner-dependent subset. Failing here would be flaky and unactionable. It is still
   reported, so a systematic install failure stays visible.

Once the committed artifacts have been regenerated by this same CI job, classes 1 and 2
should be empty in steady state, since the committed copy is then itself a prior output of
the identical command. "Steady state" is doing real work in that sentence: the generated
set reflects an *installed environment*, so a GitHub runner image refresh that moves a
preinstalled package can turn this red with the lockfile untouched. That is a true signal
about what would actually be installed, not a false positive, and it is resolved by the
same regenerate-and-commit path - but it means this gate tracks the audited environment,
not the lockfile alone.

Only the `Version` field is compared. Two reasons, the second stronger than the first:
`pip-licenses` can reformat a license string between releases ("Apache-2.0" vs "Apache
Software License"), which would be noise; and more importantly PyPI versions are immutable,
so a genuine relicensing always ships with a version bump, which trips the version check
anyway - and the mandated fix (commit the regenerated file wholesale) refreshes the license
column with it. The residual uncovered case is a license *metadata* correction published
without a version change.

Format note: this parses `pip-licenses` output, in either its JSON (a list of package
objects) or markdown-table form. `scripts/generate_sbom.sh` has a `syft` branch that
instead writes `docs/sbom.json` as SPDX-JSON - a JSON *object* - and does not write
`DEPENDENCY_LICENSES.md` at all. Feeding that here exits 2 ("not a JSON list") rather
than passing silently, which is the right failure direction, but it means the two
regeneration paths are not interchangeable. Regenerate via the `pip-licenses` path, or
via the `python-sbom` CI artifact, and treat that inconsistency as open.

Usage:
    python tools/check_sbom_freshness.py --generated sbom.json --committed docs/sbom.json
    python tools/check_sbom_freshness.py --generated fresh.md --committed docs/DEPENDENCY_LICENSES.md

CI usage (see .github/workflows/security.yml, job `python-sbom`):
    pip-licenses --format=json --output-file=sbom.json
    python tools/check_sbom_freshness.py --generated sbom.json --committed docs/sbom.json
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

# A markdown table row: | name | version | license |
_ROW_RE = re.compile(r"^\|\s*([A-Za-z0-9_.-]+)\s*\|\s*([0-9][^ |]*)\s*\|")


class ArtifactError(RuntimeError):
    """The artifact could not be parsed, or does not look like real pip-licenses output."""


def normalize(name: str) -> str:
    """PEP 503 style normalization so Foo_Bar and foo-bar compare equal."""
    return name.strip().lower().replace("_", "-")


def parse_artifact(text: str, path_hint: str) -> dict[str, str]:
    """Parse a pip-licenses artifact (json or markdown) into {package: version}.

    Raises ArtifactError on an empty or unparseable artifact. An empty artifact must
    never read as "nothing to compare, therefore fresh" - that would silently disable
    this gate exactly when the SBOM generation step had broken.
    """
    stripped = text.strip()
    if not stripped:
        raise ArtifactError(f"{path_hint} is empty")

    packages: dict[str, str] = {}

    # Detect JSON by either opening delimiter, not just "[". A JSON object starts with
    # "{", and if it fell through to the markdown branch it would parse to zero rows and
    # report a misleading "zero packages" error instead of the real problem.
    if stripped[0] in "[{":
        try:
            entries = json.loads(stripped)
        except json.JSONDecodeError as exc:
            raise ArtifactError(f"{path_hint} is not valid JSON: {exc}") from exc
        if not isinstance(entries, list):
            raise ArtifactError(
                f"{path_hint} is not a JSON list (pip-licenses --format=json emits a "
                f"list of package objects)"
            )
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            name = str(entry.get("Name", "")).strip()
            version = str(entry.get("Version", "")).strip()
            if name and version:
                packages[normalize(name)] = version
    else:
        for line in stripped.splitlines():
            m = _ROW_RE.match(line)
            if m:
                packages[normalize(m.group(1))] = m.group(2)

    if not packages:
        raise ArtifactError(
            f"{path_hint} yielded zero packages - generation or parsing failure, "
            f"not a clean comparison"
        )
    return packages


def compare(
    generated: dict[str, str], committed: dict[str, str]
) -> tuple[list[tuple[str, str, str]], list[str], list[str]]:
    """Return (drifted, undocumented, not_regenerated).

    drifted: packages in both whose versions disagree, as (package, committed, generated).
        Fatal.
    undocumented: packages the fresh run produced that the committed artifact does not
        list at all. Fatal - the committed SBOM under-reports the real dependency set,
        and this is the direction a deleted/tampered row shows up in.
    not_regenerated: packages the committed artifact lists that the fresh run did not
        produce. Reported only, never fatal: a platform-specific wheel failing to
        install on the runner is expected and not actionable.
    """
    drifted = [
        (pkg, committed[pkg], generated[pkg])
        for pkg in sorted(committed)
        if pkg in generated and committed[pkg] != generated[pkg]
    ]
    undocumented = sorted(pkg for pkg in generated if pkg not in committed)
    not_regenerated = sorted(pkg for pkg in committed if pkg not in generated)
    return drifted, undocumented, not_regenerated


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated", required=True, help="freshly generated artifact")
    parser.add_argument("--committed", required=True, help="the artifact committed under docs/")
    args = parser.parse_args(argv)

    try:
        generated = parse_artifact(
            pathlib.Path(args.generated).read_text(encoding="utf-8"), args.generated
        )
        committed = parse_artifact(
            pathlib.Path(args.committed).read_text(encoding="utf-8"), args.committed
        )
    except (OSError, ArtifactError) as exc:
        print(f"::error::cannot compare SBOM artifacts: {exc}")
        return 2

    drifted, undocumented, not_regenerated = compare(generated, committed)
    compared = len(set(generated) & set(committed))
    print(
        f"compared {compared} package(s) present in both "
        f"(generated={len(generated)}, committed={len(committed)})"
    )

    if not_regenerated:
        # Not fatal: the lockfile install step is continue-on-error, so a
        # platform-specific wheel that does not build on this runner legitimately drops
        # out of the generated set. Reported so a systematic install failure stays
        # visible rather than silently shrinking what this gate covers.
        shown = ", ".join(not_regenerated[:10])
        print(
            f"::notice::{len(not_regenerated)} package(s) listed in {args.committed} were "
            f"not produced by this run. Expected for platform-specific wheels that do not "
            f"install on the runner, and for tooling captured in whatever environment the "
            f"committed artifact was originally generated in: "
            f"{shown}{' ...' if len(not_regenerated) > 10 else ''}"
        )

    for pkg, committed_v, generated_v in drifted:
        # Deliberately says "the freshly generated artifact reports", not "the lockfile
        # resolves". The generated set comes from pip-licenses run against an installed
        # environment, which is seeded from the lockfile but is not identical to it - the
        # SBOM tooling itself and anything the runner preinstalls also appear unless
        # excluded. Naming the lockfile here would be a false attribution in a tool whose
        # whole purpose is claim accuracy.
        print(
            f"::error::{args.committed} lists {pkg}=={committed_v} but the freshly "
            f"generated artifact reports {pkg}=={generated_v}"
        )
    for pkg in undocumented:
        print(
            f"::error::{args.committed} does not list {pkg}=={generated[pkg]}, which the "
            f"freshly generated artifact reports - the committed SBOM under-reports the "
            f"dependency set"
        )

    if not drifted and not undocumented:
        print(f"{args.committed} is in sync with the freshly generated artifact.")
        return 0

    problems = []
    if drifted:
        problems.append(f"{len(drifted)} package(s) drifted")
    if undocumented:
        problems.append(f"{len(undocumented)} package(s) missing from the committed artifact")
    print(
        f"\n{'; '.join(problems)}. {args.committed} is stale.\n"
        f"To fix: download the `python-sbom` artifact from this workflow run and commit "
        f"its sbom.json and DEPENDENCY_LICENSES.md over the copies in docs/. Do not "
        f"hand-edit individual rows - that fabricates freshness in an artifact "
        f"downstream tooling reads as authoritative. If you regenerate locally instead, "
        f"use scripts/generate_sbom.sh with pip-licenses (its syft branch emits SPDX-JSON, "
        f"which is a different format this gate does not parse)."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
